[Settings]
  ID = "gophersource"

[build]
  publish = "public"
  command = "make build"

[context.production.environment]
  HUGO_VERSION = "0.46"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.46"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.46"
