[Settings]
  ID = "gophersource"

[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.48"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"
